'use client';

import { useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useProject } from '@/contexts/ProjectContext';
import type { Project } from '@/types';
import BackgroundStep from '@/components/BackgroundStep';
import ProductIntroStep from '@/components/ProductIntroStep';
import PersonaStep from '@/components/PersonaStep';
import AppearanceStep from '@/components/AppearanceStep';
import CMFStep from '@/components/CMFStep';
import StoryboardStep from '@/components/StoryboardStep';
import ExplodedViewStep from '@/components/ExplodedViewStep';
import ExportPanel from '@/components/ExportPanel';

const stepFieldMapping: Record<number, string> = {
  0: 'background',
  1: 'product_intro',
  2: 'personas',
  3: 'appearance_images',
  4: 'cmf',
  5: 'storyboard_images',
  6: 'exploded_view_image',
};

const stepNames = [
  '背景研究',
  '产品介绍',
  '用户画像',
  '外观设计',
  'CMF方案',
  '故事板',
  '爆炸图',
];

export default function ProjectPage() {
  const params = useParams();
  const router = useRouter();
  const { state, fetchProject, refreshProjectSilent, mergeImagesSilent, generateStep, nextStep, updateProject, goToStep, localUpdate, saveCurrentStep } = useProject();
  const projectId = params.projectId as string;
  const [isImageGenerating, setIsImageGenerating] = useState(false);
  const [activeImageJobs, setActiveImageJobs] = useState<any[]>([]);
  const [isExporting, setIsExporting] = useState(false);
  const autoGeneratedRef = useRef(false);
  const projectRef = useRef(state.project);
  projectRef.current = state.project;

  // 当前步骤对应的 image_jobs step key
  const currentImageStepKey =
    state.currentStep === 3 ? 'appearance' :
    state.currentStep === 5 ? 'storyboard' :
    state.currentStep === 6 ? 'exploded_view' :
    null;

  // 合并组件本地状态 + 服务端 job 状态
  const isImageJobRunning = activeImageJobs.some(job =>
    job.status === 'pending' || job.status === 'processing'
  );
  const effectiveImageGenerating = isImageGenerating || isImageJobRunning;

  // 页面级轮询：只从 image_jobs 表静默同步任务状态和图片 URL，不刷新整页
  useEffect(() => {
    if (!projectId || !currentImageStepKey) {
      setActiveImageJobs([]);
      setIsImageGenerating(false);
      return;
    }

    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | null = null;
    let polling = false;

    const pollJobs = async () => {
      if (cancelled || polling) return;
      polling = true;

      try {
        const res = await fetch(
          `/api/image/jobs?projectId=${projectId}&step=${currentImageStepKey}`,
          { cache: 'no-store', credentials: 'include' }
        );

        if (cancelled) { polling = false; return; }

        const data = await res.json();

        if (data.error) {
          // 未登录/过期 → 停止轮询，不重试
          if (res.status === 401 || data.error === '请先登录') { polling = false; return; }
          if (!cancelled) timer = setTimeout(pollJobs, 3000);
          polling = false;
          return;
        }

        const jobs: any[] = data.jobs || [];
        setActiveImageJobs(jobs);

        const running = jobs.some((job) =>
          job.status === 'pending' || job.status === 'processing'
        );
        setIsImageGenerating(running);

        // 已完成的图片：静默合并到 project state，不触发 loading/dirty
        const completedJobs = jobs.filter((job) =>
          job.status === 'completed' && job.imageUrl
        );

        if (completedJobs.length > 0) {
          if (currentImageStepKey === 'appearance') {
            const images = Array.isArray(projectRef.current?.appearance_images)
              ? [...(projectRef.current!.appearance_images! as string[])]
              : ['', '', ''];
            while (images.length < 3) images.push('');
            for (const job of completedJobs) {
              if (typeof job.slotIndex === 'number' && job.slotIndex >= 0 && job.slotIndex < images.length) {
                images[job.slotIndex] = job.imageUrl;
              }
            }
            mergeImagesSilent({ appearance_images: images });
          }

          if (currentImageStepKey === 'storyboard') {
            const storyboard = Array.isArray(projectRef.current?.storyboard_images)
              ? [...(projectRef.current!.storyboard_images! as any[])]
              : [];
            for (const job of completedJobs) {
              if (typeof job.slotIndex === 'number') {
                storyboard[job.slotIndex] = {
                  ...(storyboard[job.slotIndex] || {}),
                  url: job.imageUrl,
                };
              }
            }
            mergeImagesSilent({ storyboard_images: storyboard });
          }

          if (currentImageStepKey === 'exploded_view') {
            const job = completedJobs.find((j) => j.imageUrl);
            if (job?.imageUrl) {
              mergeImagesSilent({ exploded_view_image: job.imageUrl });
            }
          }
        }

        if (running) {
          timer = setTimeout(pollJobs, 1500);
        }
      } catch (err) {
        console.error('轮询图片任务异常:', err);
        if (!cancelled) timer = setTimeout(pollJobs, 3000);
      } finally {
        polling = false;
      }
    };

    pollJobs();

    // 切回页面时立即检查一次，不等待下一轮 1.5s
    const onVisible = () => {
      if (document.visibilityState === 'visible') {
        pollJobs();
      }
    };
    document.addEventListener('visibilitychange', onVisible);

    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
      document.removeEventListener('visibilitychange', onVisible);
    };
  }, [projectId, currentImageStepKey]);

  // Selection is DB-driven: derive URL from index
  const appearanceImages = (state.project?.appearance_images as string[]) || [];
  const selectedAppearanceIndex = state.project?.selected_appearance_index ?? null;
  const selectedAppearance =
    typeof selectedAppearanceIndex === 'number' &&
    selectedAppearanceIndex >= 0 &&
    selectedAppearanceIndex < appearanceImages.length
      ? appearanceImages[selectedAppearanceIndex] ?? null
      : null;

  // Save selection index to DB immediately
  const handleSelectAppearance = async (index: number) => {
    if (!state.project?.id) return;
    // Optimistic local update
    localUpdate('selected_appearance_index', index);
    try {
      await fetch(`/api/projects/${state.project.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ selected_appearance_index: index }),
      });
    } catch (err) {
      console.error('保存外观选择失败:', err);
    }
  };

  useEffect(() => {
    if (projectId) {
      fetchProject(projectId);
    }
  }, [projectId]);

  useEffect(() => {
    if (state.project && state.currentStep === 0 && !state.project.background && !state.isLoading && !state.error && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      generateStep(0);
    }
  }, [state.project?.id, state.currentStep, state.project?.background, state.isLoading, state.error]);

  // Prevent navigation away during export
  useEffect(() => {
    if (!isExporting) return;
    const handler = (e: BeforeUnloadEvent) => {
      e.preventDefault();
      e.returnValue = '';
    };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isExporting]);

  const handleRegenerate = async () => {
    await saveCurrentStep();
    if (state.currentStep < 7) {
      generateStep(state.currentStep, { force: true, referenceImage: selectedAppearance });
    }
  };

  const handleNextStep = async () => {
    // 图片步骤必须至少生成一张图才能继续
    if (state.currentStep === 3) {
      if (!state.project?.appearance_images?.some(Boolean)) return;
      if (state.project?.appearance_images?.some(Boolean) && !selectedAppearance) return;
    }
    if (state.currentStep === 5) {
      if (!state.project?.storyboard_images?.some(img => img.url)) return;
    }
    if (state.currentStep === 6) {
      if (!state.project?.exploded_view_image) return;
    }
    await saveCurrentStep();
    // 先保存当前步骤，再导航到下一步，避免全局loading阻塞UI
    const field = stepFieldMapping[state.currentStep];
    if (field && state.project) {
      await updateProject({ [field]: (state.project as any)[field] } as Partial<Project>);
    }
    nextStep();
  };

  const handleSkipStep = async () => {
    nextStep({ autoGenerate: false });
  };

  const renderStepContent = () => {
    const { project, currentStep, isLoading } = state;

    if (!project) return null;

    // 只在当前步骤对应的数据正在生成时才显示loading骨架屏
    // 其他已完成的步骤数据保持可见
    const isCurrentStepLoading = isLoading && !!stepFieldMapping[currentStep];

    switch (currentStep) {
      case 0:
        return (
          <BackgroundStep
            content={project.background}
            isLoading={isCurrentStepLoading}
            onUpdate={(content) => localUpdate('background', content)}
          />
        );
      case 1:
        return (
          <ProductIntroStep
            data={project.product_intro}
            isLoading={isCurrentStepLoading}
            onUpdate={(data) => localUpdate('product_intro', data)}
          />
        );
      case 2:
        return (
          <PersonaStep
            personas={project.personas}
            isLoading={isCurrentStepLoading}
            onUpdate={(personas) => localUpdate('personas', personas)}
          />
        );
      case 3:
        return (
          <AppearanceStep
            images={project.appearance_images}
            isLoading={isCurrentStepLoading}
            idea={project.idea}
            projectId={project.id}
            onUpdate={(images) => localUpdate('appearance_images', images)}
            onSelectionChange={handleSelectAppearance}
            onGeneratingChange={setIsImageGenerating}
            selectedIndex={selectedAppearanceIndex}
            onGenerated={() => { if (projectId) refreshProjectSilent(projectId); }}
          />
        );
      case 4:
        return (
          <CMFStep
            cmf={project.cmf}
            isLoading={isCurrentStepLoading}
            onUpdate={(cmf) => localUpdate('cmf', cmf)}
          />
        );
      case 5:
        return (
          <StoryboardStep
            images={project.storyboard_images}
            isLoading={isCurrentStepLoading}
            idea={project.idea}
            projectId={project.id}
            referenceImage={selectedAppearance}
            onUpdate={(images) => localUpdate('storyboard_images', images)}
            onGeneratingChange={setIsImageGenerating}
            onGenerated={() => { if (projectId) refreshProjectSilent(projectId); }}
          />
        );
      case 6:
        return (
          <ExplodedViewStep
            image={project.exploded_view_image}
            isLoading={isCurrentStepLoading}
            idea={project.idea}
            projectId={project.id}
            referenceImage={selectedAppearance}
            onUpdate={(image) => localUpdate('exploded_view_image', image)}
            onGeneratingChange={setIsImageGenerating}
            onGenerated={() => { if (projectId) refreshProjectSilent(projectId); }}
          />
        );
      case 7:
        return <ExportPanel project={project} selectedAppearance={selectedAppearance} onExportingChange={setIsExporting} />;
      default:
        return null;
    }
  };

  if (state.isLoading && !state.project) {
    return (
      <div className="df-workspace flex min-h-screen items-center justify-center">
        <div className="h-10 w-10 animate-spin rounded-full border-[3px] border-blue-100 border-t-blue-600" />
      </div>
    );
  }

  const completedStep = state.project?.current_step || 0;
  const title = (state.project?.product_intro as any)?.name || '产品设计项目';

  return (
    <div className="df-workspace min-h-screen">
      <header className="df-shell sticky top-0 z-30">
        <div className="mx-auto max-w-6xl px-4 py-4">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div className="flex items-center gap-3">
              <button
                onClick={() => !isExporting && router.push('/dashboard')}
                disabled={isExporting}
                className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700 outline-none transition hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700 active:translate-y-0 focus-visible:ring-4 focus-visible:ring-blue-100 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0"
              >
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" /></svg>
                项目列表
              </button>
              <button
                onClick={() => !isExporting && router.push('/')}
                disabled={isExporting}
                className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700 outline-none transition hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700 active:translate-y-0 focus-visible:ring-4 focus-visible:ring-blue-100 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0"
              >
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l5-5M7 10l5 5M7 10l-5 5" /></svg>
                主页
              </button>
            </div>

            <div className="min-w-0 flex-1 lg:text-center">
              <h1 className="truncate text-xl font-black tracking-tight text-slate-950">{title}</h1>
              <div className="mt-1 flex items-center gap-2 text-sm font-medium text-slate-500 lg:justify-center">
                {isExporting && (
                  <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-0.5 text-xs font-bold text-emerald-600">
                    <span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />
                    正在导出文件…
                  </span>
                )}
                {!isExporting && state.isSaving && <span>保存中...</span>}
                {!isExporting && state.lastSaved && !state.isSaving && (
                  <span>已保存 {state.lastSaved.toLocaleTimeString('zh-CN')}</span>
                )}
              </div>
            </div>

            <div className="rounded-full bg-blue-50 px-4 py-2 text-sm font-black text-blue-600">
              {state.currentStep < 7 ? `第 ${state.currentStep + 1} / 7 步` : '导出方案'}
            </div>
          </div>

          <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm shadow-blue-950/5">
            <div className="grid grid-cols-4 gap-2 sm:grid-cols-8">
              {stepNames.map((name, index) => {
                const enabled = index <= completedStep && !isExporting;
                const active = index === state.currentStep;
                return (
                  <button
                    key={index}
                    onClick={() => enabled && goToStep(index)}
                    className={`rounded-xl px-2 py-2 text-xs font-bold outline-none transition ${
                      active
                        ? 'bg-blue-600 text-white shadow-md shadow-blue-600/20'
                        : enabled
                        ? 'bg-slate-50 text-slate-600 hover:bg-blue-50 hover:text-blue-700'
                        : 'cursor-not-allowed bg-slate-50 text-slate-300'
                    }`}
                    title={name}
                  >
                    <span className="block text-[10px] opacity-70">{index + 1}</span>
                    <span className="block truncate">{name}</span>
                  </button>
                );
              })}
              <button
                onClick={() => state.project?.current_step === 7 && !isExporting && goToStep(7)}
                className={`rounded-xl px-2 py-2 text-xs font-bold outline-none transition ${
                  state.currentStep === 7
                    ? 'bg-emerald-600 text-white'
                    : state.project?.current_step === 7
                    ? 'bg-slate-50 text-slate-600 hover:bg-emerald-50 hover:text-emerald-700'
                    : 'cursor-not-allowed bg-slate-50 text-slate-300'
                }`}
                title="导出"
              >
                <span className="block text-[10px] opacity-70">8</span>
                <span className="block truncate">导出</span>
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-4 py-8">
        {state.isLoading && !state.project && (
          <div className="flex flex-col items-center justify-center py-20">
            <div className="h-10 w-10 animate-spin rounded-full border-[3px] border-blue-100 border-t-blue-600" />
            <p className="mt-4 text-sm font-medium text-slate-500">加载项目数据…</p>
          </div>
        )}
        {state.error && (
          <div className="mb-6 flex items-center justify-between rounded-2xl border border-red-100 bg-red-50 p-4 text-red-600">
            <span>{state.error}</span>
            <button
              onClick={() => { autoGeneratedRef.current = false; fetchProject(projectId); }}
              className="rounded-full bg-white px-4 py-2 text-sm font-bold text-red-600 outline-none transition hover:-translate-y-0.5 hover:bg-red-100 active:translate-y-0 focus-visible:ring-4 focus-visible:ring-red-100"
            >
              重试
            </button>
          </div>
        )}

        <div className="relative">
          <div className="pointer-events-none absolute -left-10 top-10 h-48 w-48 rounded-full bg-blue-200/30 blur-3xl" />
          <div className="relative">{renderStepContent()}</div>
        </div>

        {state.currentStep < 7 && (
          <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
            {state.currentStep > 0 && (
              <button
                onClick={async () => { await saveCurrentStep(); goToStep(state.currentStep - 1); }}
                disabled={state.isLoading || state.isSaving || effectiveImageGenerating}
                className="rounded-full border border-slate-200 bg-white px-6 py-3 font-bold text-slate-700 outline-none transition hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700 active:translate-y-0 focus-visible:ring-4 focus-visible:ring-blue-100 disabled:bg-slate-100 disabled:text-slate-400 disabled:hover:translate-y-0"
              >
                ← 上一步
              </button>
            )}
            {![3, 5, 6].includes(state.currentStep) && (
              <button
                onClick={handleRegenerate}
                disabled={state.isLoading || state.isSaving}
                className="rounded-full border border-slate-200 bg-white px-6 py-3 font-bold text-slate-700 outline-none transition hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700 active:translate-y-0 focus-visible:ring-4 focus-visible:ring-blue-100 disabled:bg-slate-100 disabled:text-slate-400 disabled:hover:translate-y-0"
              >
                {state.isLoading ? (
                  <span className="flex items-center gap-2">
                    <span className="h-4 w-4 animate-spin rounded-full border-2 border-blue-200 border-b-transparent" />
                    生成中...
                  </span>
                ) : '重新生成'}
              </button>
            )}
            {state.currentStep >= (state.project?.current_step ?? 0) && (
              <button
                onClick={handleSkipStep}
                disabled={state.isLoading || state.isSaving || effectiveImageGenerating}
                className="rounded-full border border-slate-200 bg-white px-6 py-3 font-bold text-slate-700 outline-none transition hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700 active:translate-y-0 focus-visible:ring-4 focus-visible:ring-blue-100 disabled:bg-slate-100 disabled:text-slate-400 disabled:hover:translate-y-0"
              >
                {effectiveImageGenerating ? '图片生成中…' : '跳过此部分'}
              </button>
            )}
            <button
              onClick={handleNextStep}
              disabled={state.isLoading || state.isSaving || ([3, 5, 6].includes(state.currentStep) && effectiveImageGenerating) || (state.currentStep === 3 && (!state.project?.appearance_images?.some(Boolean) || (state.project?.appearance_images?.some(Boolean) && !selectedAppearance))) || (state.currentStep === 5 && !state.project?.storyboard_images?.some(img => img.url)) || (state.currentStep === 6 && !state.project?.exploded_view_image)}
              className={`rounded-full px-7 py-3 font-bold outline-none transition hover:-translate-y-0.5 active:translate-y-0 focus-visible:ring-4 disabled:hover:translate-y-0 ${
                state.isLoading || ([3, 5, 6].includes(state.currentStep) && effectiveImageGenerating)
                  ? 'bg-slate-300 text-white'
                  : (state.currentStep === 3 && (!state.project?.appearance_images?.some(Boolean) || (state.project?.appearance_images?.some(Boolean) && !selectedAppearance))) || (state.currentStep === 5 && !state.project?.storyboard_images?.some(img => img.url)) || (state.currentStep === 6 && !state.project?.exploded_view_image)
                  ? 'bg-slate-200 text-slate-400'
                  : 'bg-blue-600 text-white shadow-md shadow-blue-600/20 hover:bg-blue-700 focus-visible:ring-blue-200'
              }`}
            >
              {state.isLoading || ([3, 5, 6].includes(state.currentStep) && effectiveImageGenerating) ? '图片生成中…' : (
                (() => {
                  const isDisabled = (state.currentStep === 3 && (!state.project?.appearance_images?.some(Boolean) || (state.project?.appearance_images?.some(Boolean) && !selectedAppearance))) || (state.currentStep === 5 && !state.project?.storyboard_images?.some(img => img.url)) || (state.currentStep === 6 && !state.project?.exploded_view_image);
                  if (isDisabled) {
                    return '请先生成图片';
                  }
                  return '满意，下一步 →';
                })()
              )}
            </button>
          </div>
        )}
      </main>
    </div>
  );
}
